inbound:
  env: NODE_ENV
  http:
    port: PORT
    host: HOST
  logger:
    level: LOG_LEVEL

outbound:
  prisma:
    databaseUrl: DATABASE_URL
  openRouter:
    apiKey: OPEN_ROUTER_API_KEY
  worldNews:
    apiKey: WORLD_NEWS_API_KEY
