inbound:
  env: production
  http:
    host: localhost
    port: 3000
  logger:
    level: info
    prettyPrint: false
  tasks:
    reportPipeline:
      - country: FR
        language: FR
      - country: US
        language: EN

outbound:
  agents:
    reportIngestion: 'moonshotai/kimi-k2-thinking'
    reportDeduplication: 'moonshotai/kimi-k2-thinking'
    reportClassification: 'moonshotai/kimi-k2-thinking'
    articleComposition: 'google/gemini-2.5-flash'
    articleFabrication: 'google/gemini-2.5-flash'
    articleQuizGeneration: 'moonshotai/kimi-k2-thinking'

  worldNews:
    useCache: false
  newRelic:
    enabled: true
