inbound:
  env: production
  http:
    host: localhost
    port: 3000
  logger:
    level: info
    prettyPrint: false
  tasks:
    reportPipeline:
      - country: FR
        language: FR
      - country: US
        language: EN

outbound:
  agents:
    reportIngestion: 'x-ai/grok-4-fast'
    reportDeduplication: 'x-ai/grok-4-fast'
    reportClassification: 'x-ai/grok-4-fast'
    articleComposition: 'google/gemini-3-pro-preview'
    articleFabrication: 'google/gemini-3-pro-preview'
    articleQuizGeneration: 'google/gemini-3-pro-preview'

  worldNews:
    useCache: false
  newRelic:
    enabled: true
