inbound:
  env: production
  http:
    host: localhost
    port: 3000
  logger:
    level: info
    prettyPrint: false
  tasks:
    storyPipeline:
      - country: fr
        language: fr
      - country: us
        language: en

outbound:
  openRouter:
    budget: high
  worldNews:
    useCache: false
  newRelic:
    enabled: true
