inbound:
  env: production
  http:
    host: localhost
    port: 3000
  logger:
    level: info
    prettyPrint: false
  tasks:
    reportPipeline:
      - country: FR
        language: FR
      - country: US
        language: EN

outbound:
  openRouter:
    budget: high
  worldNews:
    useCache: false
  newRelic:
    enabled: true
