inbound:
  env: production
  http:
    host: localhost
    port: 3000
  logger:
    level: info
    prettyPrint: false
  tasks:
    reportPipeline:
      - country: FR
        language: FR
      - country: US
        language: EN

outbound:
  agents:
    reportIngestion: 'deepseek/deepseek-v3.2'
    reportDeduplication: 'deepseek/deepseek-v3.2'
    reportClassification: 'deepseek/deepseek-v3.2'
    articleComposition: 'deepseek/deepseek-v3.2'
    articleFabrication: 'deepseek/deepseek-v3.2'
    articleQuizGeneration: 'deepseek/deepseek-v3.2'

  worldNews:
    useCache: false
  newRelic:
    enabled: true
