inbound:
  http:
    port: 3000
  logger:
    level: debug
    prettyPrint: true
  tasks:
    reportPipeline:
      - country: FR
        language: FR

outbound:
  openRouter:
    budget: low
  worldNews:
    useCache: true
